### ISSUE TITLE
lds-ripple loader looking bad on safari

### ISSUE THREAD

**Issue by rettiseert** [loadingio/css-spinner#18]
The lds-ripple effect is not working properly on safari on iOS 15 (at least on my device). The ripples are supposed to fade out as they grow and then disappear, but instead they start fading out and then they are shown in full color just before disappearing.

This is what I expect:
![image](https://user-images.githubusercontent.com/25987733/163236051-7c50c55a-a2ce-40d0-ac07-af6c3afc8f4e.png)

And this is what I see:
![image](https://user-images.githubusercontent.com/25987733/163237250-6727b967-55d4-40c8-bff5-eadfb53f4881.png)

Any chance to fix this? Thanks!

**Comment by zbryikt** [comment]
this unfortunately is likely to be a browser bug. I tried hiding ripples longer and indeed it works but I don't think it will be reliable since it may be related to how frequently Safari renders the animation.

Here is an example that hides and freezes the rings for 5% of total duration at the beginning, followed by the original animation:

https://codepen.io/plotdb/pen/rNpRYXV

Guess I can still patch with this example since it makes almost no visual difference with the  original effect.

**Comment by zbryikt** [comment]
fixed by https://github.com/loadingio/css-spinner/commit/3e7c19268e9957aa9460c3a497e85ce08dff4bbd
released as v2.0.2
https://github.com/loadingio/css-spinner/releases/tag/v2.0.2
